### ISSUE TITLE
App [default] associated with space [space-name] and userprofile [null] is not found or in unusable state. Please try again after making sure that the app is created and InService

### ISSUE THREAD

**Issue by ArtemioPadilla** [aws-samples/sagemaker-studio-apps-lifecycle-config-examples#10]
I'm getting this error sporadically since I started using the LCCs for the new SageMaker Studio:

`App [default] associated with space [space-name] and userprofile [null] is not found or in unusable state. Please try again after making sure that the app is created and InService
`

I have tried to solving it by unselecting the LCC then running the app (update the space), then shutting it down and finally selecting the LCC again. This seems to work but the error still appears periodically.

**Comment by ArtemioPadilla** [comment]
to specify: we are using the autostop LCC

**Comment by ArtemioPadilla** [comment]
From the logs I can see the LCC script runs ok. The instance is launched but then it receives a SIGTERM (I don't know why)

<img width="1015" alt="image" src="https://github.com/aws-samples/sagemaker-studio-apps-lifecycle-config-examples/assets/58867702/df9d584a-8c8e-4693-8d79-d9ddf44498b6">

**Comment by giuseppeporcelli** [comment]
Hi @ArtemioPadilla, I guess you are referring to the Code Editor auto shutdown LCC. If that is the case, are you using the code released on 03/13 (first release of the LCC https://github.com/aws-samples/sagemaker-studio-apps-lifecycle-config-examples/releases/tag/v0.3.0) ?

There was a bug in the pre-release code that we have fixed.

**Comment by ArtemioPadilla** [comment]
Hi @giuseppeporcelli
Thanks for your answer. We indeed had an old version of the LCC. I just released the new LCC to my users. We'll be testing and report back. If no problems are detected I will close this issue. Thanks for the support.

**Comment by ArtemioPadilla** [comment]
Hi @giuseppeporcelli ,

It appears that we have no issues now with the updated post-release source code.

Thanks for your support!
