### ISSUE TITLE
Can some of these LCC scripts be bundled into the Sagemaker-distribution image?

### ISSUE THREAD

**Issue by rahul-ve** [aws-samples/sagemaker-studio-apps-lifecycle-config-examples#11]
Hi Team,

We are using few  LCC scripts (git credentials, autoshutdown, docker tools) within our environment, they work ok but delay the startup of the IDE.
Just wondering if some of these scripts can be bundled into the Sagemaker-distribution images? or do they have to be installed on the EC2 host?

Thanks!

**Comment by durgasury** [comment]
Hi @rahul-ve , you can bundle them with the SageMaker Distribution images. However, today, custom images do not have the same fast launch as the default SageMaker Distribution image - so you may be looking at a longer startup time.

**Comment by rahul-ve** [comment]
Thanks @durgasury, in that case it does not make sense to spend the effort on custom images.
