### ISSUE TITLE
CodeEditor Auto Shutdown

### ISSUE THREAD

**Issue by lasmith** [aws-samples/sagemaker-studio-apps-lifecycle-config-examples#2]
I assume this script does not work on code editor space apps? 

Therefore the question / feature request is can you provide an equivalent example to auto shutdown code editor apps? Or aim me to an example on how to do this?

Thanks

Laurence

**Comment by giuseppeporcelli** [comment]
Hi, the equivalent example for Code Editor has been released:

https://github.com/aws-samples/sagemaker-studio-apps-lifecycle-config-examples/releases/tag/v0.3.0

Regards,
Giuseppe
